### ISSUE TITLE
X99 kernel kext patches

### ISSUE THREAD

**Issue by alok0182** [KGP/X99-EFI-Folder-Distributions#2]
Hi, @KGP hope you are doing well, and thanks for your contribution to the Hackintosh community. Because of you, I am able to run Mac OS on my  x99 system since 2017. I fully relied on you so I never tried to learn something like "KernelToPatch" and "KextToPatch".I know you are no longer available in any Hackintosh forum and we all are missing you very badly. Can you still help me with the "kernel kext patches" for USB port Limit or _xcpm_ performance_patch etc? or a list please tell me from where I can get those patches.

**Comment by KGP** [comment]
All necessary kext and kernel patches are part of my respective EFI-Folder distributions.
