### ISSUE TITLE
Mojave 10.14.5 performance dropped.

### ISSUE THREAD

**Issue by alok0182** [KGP/X99-EFI-Folder-Distributions#3]
After updating to 10.14.5 my CPU performance has been dropped drastically. can you please help me by providing the _xcpm_ performance_patch, _xcpm_SMT_scope_msrs 1, and _xcpm_SMT_scope_msrs 2 -- Kernel ToPatch --. I have already applied those patches from 10.14.5 Beta EFI folder you have provided but nothing happened.
I am providing my AppleIntelInfo.kext output.
AppleIntelInfo.kext v2.9 Copyright © 2012-2017 Pike R. Alpha. All rights reserved.
Settings:
------------------------------------------
logMSRs..................................: 1
logIGPU..................................: 0
logCStates...............................: 1
logIPGStyle..............................: 1
InitialTSC...............................: 0xb5a67b032b4 (367 MHz)
MWAIT C-States...........................: 8480

Processor Brandstring....................: Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz

Processor Signature..................... : 0x406F1
------------------------------------------
 - Family............................... : 6
 - Stepping............................. : 1
 - Model................................ : 0x4F (79)

Model Specific Registers (MSRs)
------------------------------------------

MSR_IA32_PLATFORM_ID.............(0x17)  : 0x8000000000000
------------------------------------------
 - Processor Flags...................... : 2

MSR_CORE_THREAD_COUNT............(0x35)  : 0x6000C
------------------------------------------
 - Core Count........................... : 6
 - Thread Count......................... : 12

MSR_PLATFORM_INFO................(0xCE)  : 0x20080C3BF3812200
------------------------------------------
 - Maximum Non-Turbo Ratio.............. : 0x22 (3400 MHz)
 - Ratio Limit for Turbo Mode........... : 1 (programmable)
 - TDP Limit for Turbo Mode............. : 1 (programmable)
 - Low Power Mode Support............... : 1 (LPM supported)
 - Number of ConfigTDP Levels........... : 1 (additional TDP level(s) available)
 - Maximum Efficiency Ratio............. : 12
 - Minimum Operating Ratio.............. : 8

MSR_PMG_CST_CONFIG_CONTROL.......(0xE2)  : 0x402
------------------------------------------
 - I/O MWAIT Redirection Enable......... : 1 (enabled, IO read of MSR(0xE4) mapped to MWAIT)
 - CFG Lock............................. : 0 (MSR not locked)
 - C3 State Auto Demotion............... : 0 (disabled/unsupported)
 - C1 State Auto Demotion............... : 0 (disabled/unsupported)
 - C3 State Undemotion.................. : 0 (disabled/unsupported)
 - C1 State Undemotion.................. : 0 (disabled/unsupported)
 - Package C-State Auto Demotion........ : 0 (disabled/unsupported)
 - Package C-State Undemotion........... : 0 (disabled/unsupported)

MSR_PMG_IO_CAPTURE_BASE..........(0xE4)  : 0x10414
------------------------------------------
 - LVL_2 Base Address................... : 0x414
 - C-state Range........................ : 1 (C6 is the max C-State to include)

IA32_MPERF.......................(0xE7)  : 0x5B79615C83
IA32_APERF.......................(0xE8)  : 0x59C389E07E
MSR_0x150........................(0x150) : 0x0

MSR_FLEX_RATIO...................(0x194) : 0xE0000
------------------------------------------

MSR_IA32_PERF_STATUS.............(0x198) : 0x192F00000C00
------------------------------------------
 - Current Performance State Value...... : 0xC00 (1200 MHz)

MSR_IA32_PERF_CONTROL............(0x199) : 0x2900
------------------------------------------
 - Target performance State Value....... : 0x2900 (4100 MHz)
 - Intel Dynamic Acceleration........... : 0 (IDA engaged)

IA32_CLOCK_MODULATION............(0x19A) : 0x0

IA32_THERM_INTERRUPT.............(0x19B) : 0x0

IA32_THERM_STATUS................(0x19C) : 0x88450000
------------------------------------------
 - Thermal Status....................... : 0
 - Thermal Log.......................... : 0
 - PROCHOT # or FORCEPR# event.......... : 0
 - PROCHOT # or FORCEPR# log............ : 0
 - Critical Temperature Status.......... : 0
 - Critical Temperature log............. : 0
 - Thermal Threshold #1 Status.......... : 0
 - Thermal Threshold #1 log............. : 0
 - Thermal Threshold #2 Status.......... : 0
 - Thermal Threshold #2 log............. : 0
 - Power Limitation Status.............. : 0
 - Power Limitation log................. : 0
 - Current Limit Status................. : 0
 - Current Limit log.................... : 0
 - Cross Domain Limit Status............ : 0
 - Cross Domain Limit log............... : 0
 - Digital Readout...................... : 69
 - Resolution in Degrees Celsius........ : 1
 - Reading Valid........................ : 1 (valid)

MSR_THERM2_CTL...................(0x19D) : 0x0

IA32_MISC_ENABLES................(0x1A0) : 0x850089
------------------------------------------
 - Fast-Strings......................... : 1 (enabled)
 - FOPCODE compatibility mode Enable.... : 0
 - Automatic Thermal Control Circuit.... : 1 (enabled)
 - Split-lock Disable................... : 0
 - Performance Monitoring............... : 1 (available)
 - Bus Lock On Cache Line Splits Disable : 0
 - Hardware prefetch Disable............ : 0
 - Processor Event Based Sampling....... : 0 (PEBS supported)
 - GV1/2 legacy Enable.................. : 0
 - Enhanced Intel SpeedStep Technology.. : 1 (enabled)
 - MONITOR FSM.......................... : 1 (MONITOR/MWAIT supported)
 - Adjacent sector prefetch Disable..... : 0
 - CFG Lock............................. : 0 (MSR not locked)
 - xTPR Message Disable................. : 1 (disabled)

MSR_TEMPERATURE_TARGET...........(0x1A2) : 0x640A00
------------------------------------------
 - Turbo Attenuation Units.............. : 0 
 - Temperature Target................... : 100
 - TCC Activation Offset................ : 0

MSR_MISC_PWR_MGMT................(0x1AA) : 0x402000
------------------------------------------
 - EIST Hardware Coordination........... : 0 (hardware coordination enabled)
 - Energy/Performance Bias support...... : 1
 - Energy/Performance Bias.............. : 0 (disabled/MSR not visible to software)
 - Thermal Interrupt Coordination Enable : 1 (thermal interrupt routed to all cores)
 - SpeedShift Technology Enable......... : 0 (disabled)
 - SpeedShift Interrupt Coordination.... : 0 (disabled)
 - SpeedShift Energy Efficient Perf..... : 0 (disabled)
 - SpeedShift Technology Setup for HWP.. : No (not setup for HWP)

MSR_TURBO_RATIO_LIMIT............(0x1AD) : 0x2323292929292929
------------------------------------------
 - Maximum Ratio Limit for C01.......... : 29 (4100 MHz) 
 - Maximum Ratio Limit for C02.......... : 29 (4100 MHz) 
 - Maximum Ratio Limit for C03.......... : 29 (4100 MHz) 
 - Maximum Ratio Limit for C04.......... : 29 (4100 MHz) 
 - Maximum Ratio Limit for C05.......... : 29 (4100 MHz) 
 - Maximum Ratio Limit for C06.......... : 29 (4100 MHz) 

IA32_ENERGY_PERF_BIAS............(0x1B0) : 0x1
------------------------------------------
 - Power Policy Preference...............: 1 (highest performance)

MSR_POWER_CTL....................(0x1FC) : 0x2904005B
------------------------------------------
 - Bi-Directional Processor Hot..........: 1 (enabled)
 - C1E Enable............................: 1 (enabled)

MSR_RAPL_POWER_UNIT..............(0x606) : 0xA0E03
------------------------------------------
 - Power Units.......................... : 3 (1/8 Watt)
 - Energy Status Units.................. : 14 (61 micro-Joules)
 - Time Units .......................... : 10 (976.6 micro-Seconds)

MSR_PKG_POWER_LIMIT..............(0x610) : 0x7FFF80015FFF8
------------------------------------------
 - Package Power Limit #1............... : 4095 Watt
 - Enable Power Limit #1................ : 1 (enabled)
 - Package Clamping Limitation #1....... : 1 (allow going below OS-requested P/T state during Time Window for Power Limit #1)
 - Time Window for Power Limit #1....... : 10 (2560 milli-Seconds)
 - Package Power Limit #2............... : 4095 Watt
 - Enable Power Limit #2................ : 1 (enabled)
 - Package Clamping Limitation #2....... : 1 (allow going below OS-requested P/T state setting Time Window for Power Limit #2)
 - Time Window for Power Limit #2....... : 3 (20 milli-Seconds)
 - Lock................................. : 0 (MSR not locked)

MSR_PKG_ENERGY_STATUS............(0x611) : 0x8E982C9
------------------------------------------
 - Total Energy Consumed................ : 9126 Joules (Watt = Joules / seconds)

MSR_PKGC3_IRTL...................(0x60a) : 0x0
MSR_PKGC6_IRTL...................(0x60b) : 0x0
MSR_PKGC7_IRTL...................(0x60c) : 0x0
MSR_PKG_C2_RESIDENCY.............(0x60d) : 0x2B4C528A12
MSR_PKG_C3_RESIDENCY.............(0x3f8) : 0x0
MSR_PKG_C2_RESIDENCY.............(0x60d) : 0x2B4C541EC0
MSR_PKG_C6_RESIDENCY.............(0x3f9) : 0x5ED09967E0
MSR_PKG_C7_RESIDENCY.............(0x3fa) : 0x0

IA32_TSC_DEADLINE................(0x6E0) : 0xB5A76080697

CPU Ratio Info:
------------------------------------------
Base Clock Frequency (BLCK)............. : 100 MHz
Maximum Efficiency Ratio/Frequency.......: 12 (1200 MHz)
Maximum non-Turbo Ratio/Frequency........: 34 (3400 MHz)
Maximum Turbo Ratio/Frequency............: 41 (4100 MHz)
P-State ratio * 100 = Frequency in MHz
------------------------------------------
CPU P-States [ (12) 33 34 ]
CPU C6-Cores [ 0 2 4 6 8 11 ]
CPU P-States [ (12) 23 33 34 ]
CPU C6-Cores [ 0 2 3 4 5 6 8 9 10 11 ]
CPU P-States [ (12) 23 26 33 34 ]
CPU C6-Cores [ 0 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ (12) 23 26 30 33 34 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ 12 23 24 26 30 33 34 (41) ]
CPU P-States [ (12) 21 23 24 26 30 33 34 41 ]
CPU P-States [ (12) 21 23 24 26 28 30 33 34 41 ]
CPU P-States [ (12) 20 21 23 24 26 28 30 33 34 41 ]

**Comment by KGP** [comment]
My friend, I retired from the Hackintosh community. All necessary and valid xcpm kernel patches are part of the config.plist of my 10.14.5 Beta EFI-Folder distribution. I do not observe any CPU performance drop with this xcpm kernel patch configuration. Else see  https://kgp-hackintosh-corner.com/just-to-keep-alive. 

Good luck

**Comment by sincohen** [comment]
> My friend, I retired from the Hackintosh community. All necessary and valid xcpm kernel patches are part of the config.plist of my 10.14.5 Beta EFI-Folder distribution....

@KGP you were the absolute best. why did you retire? So many of us really look to your work and ability to organize the work of others in such a thorough and informative way.
